version: "3"
services:
  web:
    build: ./hangboard-web
    ports: ['8080:8080']
  exercise:
    build: ./exercises
    ports: [4321:4321]
  force:
    build: ./hardware/force_sensors
    ports: [4322:4322]

#  sensors:
#    build: ./hardware
    #devices:
    #  - /dev/gpiomem:/dev/gpiomem