version: "3"
services:
  web:
    build: ./hangboard-app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./main.py
      HOST: exercise
      PORT: 9090
      PORTRECV: 9091
    ports: ['8080:5000']
    volumes: ['./hangboard-app:/app']
  exercise:
    build: ./exercises
    entrypoint:
      - ./startup.sh
    environment: 
      HOST: exercise
      PORT: 9090
      PORTRECV: 9091
    volumes: ['./exercises:/app']    