#!/bin/bash
branch=main
git checkout gh-pages --quiet

git rm -r * --quiet

git checkout $branch -- .gitignore
git checkout $branch -- doc
git checkout $branch -- backend

echo "Build API documentation"
echo "npm install -g @asyncapi/generator"
rm -rf api
mkdir api
cd backend ; ag asyncapi.yaml @asyncapi/html-template -o ../api/ ; cd ..

echo "Build backend documentation"
rm -rf backend-doc
rm -rf backend/doxygen
cd backend ; doxygen ;cd ..
mv backend/doxygen/html backend-doc

echo "Build manual"
asciidoctor -d book -D ./doc --backend=html5 -o ./index.html doc/Manual.adoc

git add -A
git commit -a -m  "updated $(date +"%d.%m.%Y %H:%M:%S")"
git push --quiet

git checkout $branch --quiet
