name: AsyncAPI documents processing

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2
      
    #Using another action for AsyncAPI for validation
    # - name: Validating AsyncAPI document
    #   uses: WaleedAshraf/asyncapi-github-action@v1
    #   with:
    #     filepath: backend/asyncapi.yaml
      
    #In case you do not want to use defaults, you for example want to use different template
    - name: Generating HTML from my AsyncAPI document
      uses: asyncapi/github-action-for-generator@v1
      with:
        #template: '@asyncapi/html-template@0.9.0'  #In case of template from npm, because of @ it must be in quotes
        template: '@asyncapi/html-template'  #In case of template from npm, because of @ it must be in quotes
        filepath: backend/asyncapi.yaml
        parameters: baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
        output: generated-html
      
    #Using another action that takes generated HTML and pushes it to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: generated-html

