# name: Publish to GitHub Pages

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - uses: subosito/flutter-action@v1
#       - run: cd flutter_hangboard ; flutter pub get
#       - run: cd flutter_hangboard ; flutter build web
#       - uses: erickzanardo/flutter-gh-pages@v3
#         with:
#           workingDir: flutter_hangboard
